name: CD
on:
  workflow_run:
    types: [completed]
    branches: [main]
    workflows: ["CI"]

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t user/app:latest .

      - name: Run container
        run: docker run -d -p 8080:8080 user/app:latest